Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :private_network, ip: '192.168.42.43' 
  config.vm.provision :shell,
    :inline => "sudo apt-get update && sudo apt-get install -y python-software-properties && sudo apt-add-repository ppa:brightbox/ruby-ng && sudo apt-get update && sudo apt-get -y install build-essential git ruby2.2 ruby2.2-dev nodejs curl && sudo gem install github-pages typhoeus flickraw --no-ri --no-rdoc && cd jekyll && jekyll serve -P 80 --watch --detach --force_polling"

  config.vm.hostname = 'andybateman.local'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.ssh.forward_agent = true
  config.vm.synced_folder "jekyll", "/home/vagrant/jekyll"
end
