# Site settings
title: Andy Bateman
email: andy@andybateman.com
description: Andy Bateman is just some guy, a very modest guy, you know?
baseurl: ""
url: "https://www.andybateman.com"
twitter_username: andybateman
facebook_username: andybateman
permalink: /:categories/:title/

sass:
  sass_dir: _scss
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from